mysite/cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls')),
    path('user/', include('user.urls')),
    path('payments/', include('payments.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        # ...
        path("__debug__/", include("debug_toolbar.urls")),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

mysite/cart/models.py
from django.db import models

# Create your models here.

mysite/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False,initial=False, widget=forms.HiddenInput)

mysite/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])

    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    context = {'cart': cart}
    return render(request, 'cart/detail.html', context=context)


# def cart_detail(request):
#     cart = Cart(request)
#     for item in cart:
#         item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
#     return render(request, 'cart/detail.html', {'cart': cart})

mysite/cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>Ваша корзина покупок</h1>
    {% for item in cart %}
        {% with product=item.product %}
            {{ product.title }}
        {% endwith %}
    {% endfor %}
    <table class="cart">
        <thead>
        <tr>
            <th>Изображение</th>
            <th>Наименованиеt</th>
            <th>Кол-во</th>
            <th>Удалить</th>
            <th>Цена</th>
            <th>Стоимость</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image %}{{ product.image.url }}
                            {% else %}
                            No foto
{#                                {{ product.image.url }}#}
                            {% endif %}">
                        </a>
                    </td>
                    <td>{{ product.title }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>
                        <form action="{% url "cart:cart_remove" product.id %}" method="post">
                            <input type="submit" value="Remove">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Итого:</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="#" class="button light">Продолжить</a>
        <a href="{% url 'orders:order_create' %}" class="button">Оформить</a>
    </p>
{% endblock %}